# Deep Learning : Keras

🎥 [08. Deep Learning Course Video](https://www.udemy.com/course/nlp-natural-language-processing-with-python/learn/lecture/12972006#overview)

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
X = iris.data
# X

In [5]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# class 0 -> [1,0,0]
# class 1 -> [0,1,0]
# class 2 -> [0,0,1]

In [7]:
from keras.utils import to_categorical
y = to_categorical(y)
# y

Using TensorFlow backend.


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
# min max scaling simply scales the data to be between 0 and 1
# it does this by dividing the data by the max value
# example
np.array([5,10,15,20]) / 20

array([0.25, 0.5 , 0.75, 1.  ])

In [12]:
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)
# all between 0 and 1 now
# scaled_X_train

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_dim=4))
model.add(Dense(units=8, activation='relu', input_dim=4))
model.add(Dense(units=3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [15]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(scaled_X_train, y_train, epochs=150, batch_size=10, verbose=2)

Epoch 1/150
 - 0s - loss: 1.0916 - acc: 0.3500
Epoch 2/150
 - 0s - loss: 1.0810 - acc: 0.4000
Epoch 3/150
 - 0s - loss: 1.0710 - acc: 0.4600
Epoch 4/150
 - 0s - loss: 1.0608 - acc: 0.5500
Epoch 5/150
 - 0s - loss: 1.0500 - acc: 0.6200
Epoch 6/150
 - 0s - loss: 1.0392 - acc: 0.6300
Epoch 7/150
 - 0s - loss: 1.0276 - acc: 0.6300
Epoch 8/150
 - 0s - loss: 1.0154 - acc: 0.6600
Epoch 9/150
 - 0s - loss: 1.0022 - acc: 0.6600
Epoch 10/150
 - 0s - loss: 0.9881 - acc: 0.6600
Epoch 11/150
 - 0s - loss: 0.9725 - acc: 0.6600
Epoch 12/150
 - 0s - loss: 0.9570 - acc: 0.6600
Epoch 13/150
 - 0s - loss: 0.9391 - acc: 0.6600
Epoch 14/150
 - 0s - loss: 0.9213 - acc: 0.6500
Epoch 15/150
 - 0s - loss: 0.9028 - acc: 0.6700
Epoch 16/150
 - 0s - loss: 0.8836 - acc: 0.6700
Epoch 17/150
 - 0s - loss: 0.8644 - acc: 0.6700
Epoch 18/150
 - 0s - loss: 0.8458 - acc: 0.6800
Epoch 19/150
 - 0s - loss: 0.8255 - acc: 0.6400
Epoch 20/150
 - 0s - loss: 0.8069 - acc: 0.6900
Epoch 21/150
 - 0s - loss: 0.7891 - acc: 0.6500
E

In [19]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [20]:
# remember we 1-hot-encoded the y_test

In [21]:
predictions = model.predict_classes(scaled_X_test)
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [23]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]])

In [24]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [25]:
accuracy_score(y_test.argmax(axis=1), predictions)

0.96

# Saving and Loading your model

In [26]:
model.save('my_first_model.h5')

In [27]:
from keras.models import load_model
my_model = load_model('my_first_model.h5')